### ISSUE TITLE
help commands not working

### ISSUE THREAD

**Issue by pkojopeer** [mend-dev/TestingConsole#2]
commands not working

**Comment by Peca21** [comment]
same
` Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation.CreateTowerAt(UnityEngine.Vector2, Il2CppAssets.Scripts.Models.Towers.TowerModel, Il2CppAssets.Scripts.ObjectId, Boolean, Il2CppSystem.Action1<Boolean>, Boolean, Boolean)'.
   at TestingConsole.ConsoleUi.SubmitCommand()
   at TestingConsole.ConsoleUi.<>c__DisplayClass4_0.<CreateConsole>b__0() in /home/runner/work/TestingConsole/TestingConsole/TestingConsole/TestingConsole.cs:line 177
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )`

**Comment by Symmettry** [comment]
same error

**Comment by Rndomm** [comment]
doesn't work for me either
